// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SignIn struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type SignUp struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}
